" Name:         Desert Night
" Description:  🏜️  Dark, Warm, Eye-friendly Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-desert-night/
" License:      MIT && Anti-996
" Last Updated: Wed 10 Jul 2019 03:05:13 PM CST

" Generated by Colortemplate v2.0.0b3

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'desert-night'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Structure Type
hi! link Define PreProc
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#473f31', '#e56b55', '#99b05f', '#e18245',
        \ '#949fb4', '#d261a5', '#bfab36', '#d4b07b', '#473f31', '#e56b55',
        \ '#99b05f', '#e5a440', '#949fb4', '#d261a5', '#bfab36', '#d4b07b']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#303a1a guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#1e2c3e guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#562022 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#512c13 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#473f31 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#24221c guibg=#87765d guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#473f31 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#473f31 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#24221c guibg=#99b05f guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#24221c guibg=#d4b07b guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#949fb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#473f31 guisp=NONE gui=underline cterm=underline
  hi SignColumn guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#e56b55 guibg=NONE guisp=#e56b55 gui=NONE cterm=NONE
  hi SpellCap guifg=#e18245 guibg=NONE guisp=#e18245 gui=NONE cterm=NONE
  hi SpellLocal guifg=#949fb4 guibg=NONE guisp=#949fb4 gui=NONE cterm=NONE
  hi SpellRare guifg=#d261a5 guibg=NONE guisp=#d261a5 gui=NONE cterm=NONE
  hi WildMenu guifg=#24221c guibg=#87765d guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#24221c guibg=#87765d guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#473f31 guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#473f31 guisp=NONE gui=italic cterm=italic
  hi PreCondit guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#e56b55 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Typedef guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#87765d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#87765d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#d4b07b guibg=#24221c guisp=NONE gui=bold cterm=bold
  hi markdownLinkText guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#bfab36 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownListMarker guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCodeDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownId guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownIdDeclaration guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownHeadingDelimiter guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdListItem guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdInlineURL guifg=#e5a440 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdLink guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdURL guifg=#bfab36 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdCodeDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdID guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdCode guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdHeading guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi htmlItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=250 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=250 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=250 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=235 cterm=NONE
  hi Conceal ctermfg=240 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=250 ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi CursorLineNr ctermfg=250 ctermbg=233 cterm=NONE
  hi LineNr ctermfg=240 ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=64 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=24 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=124 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=136 cterm=NONE
  hi Directory ctermfg=120 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=233 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=208 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=235 ctermbg=240 cterm=bold
  hi MoreMsg ctermfg=250 ctermbg=233 cterm=NONE
  hi FoldColumn ctermfg=240 ctermbg=233 cterm=NONE
  hi Folded ctermfg=240 ctermbg=233 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=233 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=233 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=250 ctermbg=233 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=233 cterm=NONE
  hi PmenuSel ctermfg=235 ctermbg=120 cterm=NONE
  hi PmenuThumb ctermfg=235 ctermbg=250 cterm=NONE
  hi Question ctermfg=81 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=233 cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=208 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=81 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=139 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=240 cterm=NONE
  hi StatusLine ctermfg=250 ctermbg=233 cterm=NONE
  hi StatusLineNC ctermfg=250 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=250 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=250 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=235 ctermbg=240 cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=233 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=233 cterm=italic
  hi PreCondit ctermfg=208 ctermbg=NONE cterm=NONE
  hi Title ctermfg=203 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=203 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=NONE cterm=bold
  hi Typedef ctermfg=203 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=203 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=203 ctermbg=NONE cterm=NONE
  hi Label ctermfg=208 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=208 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=208 ctermbg=NONE cterm=NONE
  hi Type ctermfg=214 ctermbg=NONE cterm=NONE
  hi Function ctermfg=120 ctermbg=NONE cterm=NONE
  hi Special ctermfg=120 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=120 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=120 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=120 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=120 ctermbg=NONE cterm=NONE
  hi String ctermfg=192 ctermbg=NONE cterm=NONE
  hi Character ctermfg=192 ctermbg=NONE cterm=NONE
  hi Number ctermfg=192 ctermbg=NONE cterm=NONE
  hi Float ctermfg=192 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=120 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=120 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=120 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=240 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=240 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi ToolbarButton ctermfg=250 ctermbg=235 cterm=bold
  hi markdownLinkText ctermfg=208 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=192 ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=214 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=120 ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=214 ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=203 ctermbg=NONE cterm=NONE
  hi markdownHeadingDelimiter ctermfg=208 ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=214 ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=214 ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=208 ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=192 ctermbg=NONE cterm=underline
  hi mkdCodeDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi mkdID ctermfg=214 ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=203 ctermbg=NONE cterm=NONE
  hi mkdCode ctermfg=120 ctermbg=NONE cterm=NONE
  hi mkdHeading ctermfg=208 ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=Grey cterm=NONE
  hi LineNr ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=Black cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=bold
  hi MoreMsg ctermfg=White ctermbg=Grey cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=Grey cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=Green cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=White cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=Grey cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi TabLine ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Grey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=Grey cterm=italic
  hi PreCondit ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=bold
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Red ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  hi Special ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Green ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Green ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Character ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Float ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Green ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Green ctermbg=NONE cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi markdownLinkText ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=Red ctermbg=NONE cterm=NONE
  hi markdownHeadingDelimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=Yellow ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi mkdCodeDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi mkdID ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=Red ctermbg=NONE cterm=NONE
  hi mkdCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi mkdHeading ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #24221c           235               Black
" Color: grey          #473f31           233               Grey
" Color: lightgrey     #87765d           240               LightGrey
" Color: golden        #d4b07b           250               White
" Color: red           #e56b55           203               Red
" Color: orange        #e18245           208               DarkYellow
" Color: yellow        #e5a440           214               Yellow
" Color: lemon         #bfab36           192               LightGreen
" Color: green         #99b05f           120               Green
" Color: brown         #bd975f           248               Brown
" Color: blue          #949fb4           81                Blue
" Color: magenta       #d261a5           139               Magenta
" Color: darkorange    #512c13           136               Black
" Color: darkred       #562022           124               Black
" Color: darkgreen     #303a1a           64                Black
" Color: darkblue      #1e2c3e           24                Black
" Term colors: grey red green orange blue magenta lemon golden
" Term colors: grey red green yellow
" Term colors: blue magenta lemon golden
" Color: unused #000000 0 0
