" Name:         Desert Night
" Description:  🏜️  Dark, Warm, Eye-friendly Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-desert-night/
" License:      MIT && Anti-996
" Last Updated: Thu 18 Jul 2019 03:26:36 PM CST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'desert-night'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Structure Type
hi! link Define PreProc
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#473f31', '#e56b55', '#99b05f', '#e18245',
        \ '#949fb4', '#d261a5', '#bfab36', '#d4b07b', '#473f31', '#e56b55',
        \ '#99b05f', '#e5a440', '#949fb4', '#d261a5', '#bfab36', '#d4b07b']
  if has('nvim')
    let g:terminal_color_0 = '#473f31'
    let g:terminal_color_1 = '#e56b55'
    let g:terminal_color_2 = '#99b05f'
    let g:terminal_color_3 = '#e18245'
    let g:terminal_color_4 = '#949fb4'
    let g:terminal_color_5 = '#d261a5'
    let g:terminal_color_6 = '#bfab36'
    let g:terminal_color_7 = '#d4b07b'
    let g:terminal_color_8 = '#473f31'
    let g:terminal_color_9 = '#e56b55'
    let g:terminal_color_10 = '#99b05f'
    let g:terminal_color_11 = '#e5a440'
    let g:terminal_color_12 = '#949fb4'
    let g:terminal_color_13 = '#d261a5'
    let g:terminal_color_14 = '#bfab36'
    let g:terminal_color_15 = '#d4b07b'
  endif
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#303a1a guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#1e2c3e guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#562022 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#512c13 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#473f31 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#24221c guibg=#87765d guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#473f31 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#473f31 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#24221c guibg=#99b05f guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#24221c guibg=#d4b07b guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#949fb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#473f31 guisp=NONE gui=underline cterm=underline
  hi SignColumn guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#e56b55 guibg=NONE guisp=#e56b55 gui=NONE cterm=NONE
  hi SpellCap guifg=#e18245 guibg=NONE guisp=#e18245 gui=NONE cterm=NONE
  hi SpellLocal guifg=#949fb4 guibg=NONE guisp=#949fb4 gui=NONE cterm=NONE
  hi SpellRare guifg=#d261a5 guibg=NONE guisp=#d261a5 gui=NONE cterm=NONE
  hi WildMenu guifg=#24221c guibg=#87765d guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#24221c guibg=#87765d guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#473f31 guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#473f31 guisp=NONE gui=italic cterm=italic
  hi PreCondit guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#87765d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#87765d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#d4b07b guibg=#24221c guisp=NONE gui=bold cterm=bold
  hi markdownLinkText guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#bfab36 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownListMarker guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCodeDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownId guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownIdDeclaration guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownHeadingDelimiter guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdListItem guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdInlineURL guifg=#e5a440 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdLink guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdURL guifg=#bfab36 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdCodeDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdID guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdCode guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdHeading guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstInlineLiteral guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstTableLines guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texOnlyMath guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texSection guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texBeginEndName guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlArg guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTag guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi xmlEndTag guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlAttrib guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssUnitDecorators guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssFunctionName guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssAttr guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssColor guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssImportant guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssTagName guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi sassClassChar guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassMixinName guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssForKeyword guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssInterpolationDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssFunctionName guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssDefault guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssMixinName guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lessClass guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lessMixinChar guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaScriptBraces Delimiter
  hi! link javaScriptParens Delimiter
  hi javaScriptFunction guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptGlobal guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptNull guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptOperator guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsOperatorKeyword guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFunction guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsArrowFunction guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi typescriptLabel guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptLogicSymbols guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptInterpolationDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptBranch guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartTypedef guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartInterpolation guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartBranch guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartCoreClasses guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartConstant guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeSpecialVar guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeSpecialIdent guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeInterp guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeInterpDelim guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptModuleParams guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptOperatorTypeSig guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptOperatorFunction guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScopeDecl guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaVarArg guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaStatement guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaTypedef guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaAnnotation guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktModifier guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktStructure guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktStatement guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonBuiltinFunc guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDecorator guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonNone guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPackage guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goImport guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goStatement guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustKeyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustExternCrate guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustModPath guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustModPathSep guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustSelf guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustLifetime guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustAssert guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpVarSelector guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMethod guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMethodsVar guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMemberSelector guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpUseClass guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpUseAlias guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpFunction guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpFunctions guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClass guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClassExtends guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpType guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpNullValue guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClassImplements guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi csUnspecifiedStatement guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csModifier guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csUnsupportedStatement guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csLogicSymbols guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csContextualStatement guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNewType guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csConstant guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csAsync guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi fsharpModifier guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpKeyChar guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpLinq guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpCoreClass guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpAttribute guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpOption guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi swiftInterpolatedString guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi swiftTypeDeclaration guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyModuleName guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyClass guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyPseudoVariable guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyDefine guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyModule guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyConstant guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyMethodName guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyControl guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyInterpolation guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyInterpolationDelimiter guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyBoolean guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyCurlyBlockDelimiter guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyBlockParameterList guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rubySymbol Identifier
  hi perlStatementPackage guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi perlMethod guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementList guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlFunction guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlSubName guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDeclKeyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDecl guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi HaskellDerive guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellWhere guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellLet guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaLocal guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncCall guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaSpecialTable guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncKeyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaSpecialValue guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonInterpDelim guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonInterp guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonSpecialOp guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dScopeDecl guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dImport guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi paramlist guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dEnum guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dConstant guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dTypedef guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dBranch guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaKeywordModifier guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaSpecial guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link scalaSquareBracketsBrackets Delimiter
  hi elixirBoolean guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link elixirTupleDelimiter Delimiter
  hi elixirPrivateDefine guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirAtom guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirKeyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlSigEncl guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlKeyChar guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlArrow guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlModule guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlModParam guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlModParam1 guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlStructEncl guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlFullMod guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlFuncWith guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlConstructor guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ocamlModPath guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranStructure guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranUnitHeader guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranCall guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranReadWrite guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fortranIO guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureDefine guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureSpecial guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi clojureDispatch guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangAtom guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangLocalFuncRef guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangType guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangLocalFuncCall guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangGlobalFuncCall guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangMap guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi erlangVariable guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispFunc guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispKey guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispDecl guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispVar guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lispEscapeSpecial guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shFunction guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDerefSimple guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shTestOpr guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shFunctionOne guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shCommandSub guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link shQuote Delimiter
  hi! link shCmdSubRegion Delimiter
  hi! link shRange Delimiter
  hi zshSubst guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshDeref guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshOptStart guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshOption guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshVariableDef guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshFunction guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshShortDeref guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link zshSubstDelim Delimiter
  hi fishKeyword guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimMap guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimFuncName guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimFunction guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimOperParen guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimOption guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimLet guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimOption guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimSetEqual guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimAutoCmd guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTable guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffAdded guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffOldFile guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffNewFile guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffFile guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link diffLine Comment
  hi helpHyperTextEntry guifg=#e56b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link helpSectionDelim Comment
  hi helpNote guifg=#949fb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpURL guifg=#bfab36 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi helpCommand guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpExample guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#e18245 guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#e56b55 guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#949fb4 guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#562022 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#512c13 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeDirSlash guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link NERDTreeLinkFile Comment
  hi NERDTreeLinkTarget guifg=#99b05f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyNumber guifg=#e5a440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFile guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySpecial guifg=#bfab36 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Sneak guifg=NONE guibg=#303a1a guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi htmlItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=250 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=250 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=250 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=235 cterm=NONE
  hi Conceal ctermfg=240 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi CursorLineNr ctermfg=250 ctermbg=233 cterm=NONE
  hi LineNr ctermfg=240 ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=64 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=24 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=124 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=136 cterm=NONE
  hi Directory ctermfg=120 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=233 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=208 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=235 ctermbg=240 cterm=bold
  hi MoreMsg ctermfg=250 ctermbg=233 cterm=NONE
  hi FoldColumn ctermfg=240 ctermbg=233 cterm=NONE
  hi Folded ctermfg=240 ctermbg=233 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=233 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=233 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=250 ctermbg=233 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=233 cterm=NONE
  hi PmenuSel ctermfg=235 ctermbg=120 cterm=NONE
  hi PmenuThumb ctermfg=235 ctermbg=250 cterm=NONE
  hi Question ctermfg=81 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=233 cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=208 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=81 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=139 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=240 cterm=NONE
  hi StatusLine ctermfg=250 ctermbg=233 cterm=NONE
  hi StatusLineNC ctermfg=250 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=250 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=250 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=235 ctermbg=240 cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=233 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=233 cterm=italic
  hi PreCondit ctermfg=208 ctermbg=NONE cterm=NONE
  hi Title ctermfg=203 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=203 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=203 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=203 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=203 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=203 ctermbg=NONE cterm=NONE
  hi Label ctermfg=208 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=208 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=208 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=208 ctermbg=NONE cterm=NONE
  hi Type ctermfg=214 ctermbg=NONE cterm=NONE
  hi Function ctermfg=120 ctermbg=NONE cterm=NONE
  hi Special ctermfg=120 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=120 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=120 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=120 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=120 ctermbg=NONE cterm=NONE
  hi String ctermfg=192 ctermbg=NONE cterm=NONE
  hi Character ctermfg=192 ctermbg=NONE cterm=NONE
  hi Number ctermfg=192 ctermbg=NONE cterm=NONE
  hi Float ctermfg=192 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=120 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=120 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=240 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=240 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi ToolbarButton ctermfg=250 ctermbg=235 cterm=bold
  hi markdownLinkText ctermfg=208 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=192 ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=214 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=120 ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=214 ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=203 ctermbg=NONE cterm=NONE
  hi markdownHeadingDelimiter ctermfg=208 ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=214 ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=214 ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=208 ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=192 ctermbg=NONE cterm=underline
  hi mkdCodeDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi mkdID ctermfg=214 ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=203 ctermbg=NONE cterm=NONE
  hi mkdCode ctermfg=120 ctermbg=NONE cterm=NONE
  hi mkdHeading ctermfg=208 ctermbg=NONE cterm=NONE
  hi rstInlineLiteral ctermfg=120 ctermbg=NONE cterm=NONE
  hi rstTableLines ctermfg=192 ctermbg=NONE cterm=NONE
  hi texOnlyMath ctermfg=208 ctermbg=NONE cterm=NONE
  hi texSection ctermfg=208 ctermbg=NONE cterm=NONE
  hi texBeginEndName ctermfg=203 ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=208 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=120 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=192 ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi xmlEndTag ctermfg=192 ctermbg=NONE cterm=NONE
  hi xmlAttrib ctermfg=208 ctermbg=NONE cterm=NONE
  hi cssUnitDecorators ctermfg=120 ctermbg=NONE cterm=NONE
  hi cssFunctionName ctermfg=214 ctermbg=NONE cterm=NONE
  hi cssAttr ctermfg=192 ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=192 ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=203 ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=214 ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi sassClassChar ctermfg=208 ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=203 ctermbg=NONE cterm=NONE
  hi scssForKeyword ctermfg=203 ctermbg=NONE cterm=NONE
  hi scssInterpolationDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi scssFunctionName ctermfg=214 ctermbg=NONE cterm=NONE
  hi scssDefault ctermfg=203 ctermbg=NONE cterm=NONE
  hi scssMixinName ctermfg=203 ctermbg=NONE cterm=NONE
  hi lessClass ctermfg=214 ctermbg=NONE cterm=NONE
  hi lessMixinChar ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link javaScriptBraces Delimiter
  hi! link javaScriptParens Delimiter
  hi javaScriptFunction ctermfg=208 ctermbg=NONE cterm=NONE
  hi javaScriptGlobal ctermfg=214 ctermbg=NONE cterm=NONE
  hi javaScriptNull ctermfg=214 ctermbg=NONE cterm=NONE
  hi javaScriptOperator ctermfg=203 ctermbg=NONE cterm=NONE
  hi jsOperatorKeyword ctermfg=203 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=214 ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=208 ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi typescriptLabel ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects ctermfg=214 ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator ctermfg=203 ctermbg=NONE cterm=NONE
  hi typescriptInterpolationDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi typescriptBranch ctermfg=208 ctermbg=NONE cterm=NONE
  hi dartTypedef ctermfg=203 ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=120 ctermbg=NONE cterm=NONE
  hi dartBranch ctermfg=208 ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=120 ctermbg=NONE cterm=NONE
  hi dartConstant ctermfg=214 ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeSpecialVar ctermfg=120 ctermbg=NONE cterm=NONE
  hi coffeeSpecialIdent ctermfg=214 ctermbg=NONE cterm=NONE
  hi coffeeInterp ctermfg=120 ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=192 ctermbg=NONE cterm=NONE
  hi purescriptModuleParams ctermfg=120 ctermbg=NONE cterm=NONE
  hi purescriptOperatorTypeSig ctermfg=203 ctermbg=NONE cterm=NONE
  hi purescriptOperatorFunction ctermfg=120 ctermbg=NONE cterm=NONE
  hi javaScopeDecl ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaVarArg ctermfg=120 ctermbg=NONE cterm=NONE
  hi javaStatement ctermfg=120 ctermbg=NONE cterm=NONE
  hi javaTypedef ctermfg=208 ctermbg=NONE cterm=NONE
  hi javaAnnotation ctermfg=120 ctermbg=NONE cterm=NONE
  hi ktModifier ctermfg=203 ctermbg=NONE cterm=NONE
  hi ktStructure ctermfg=208 ctermbg=NONE cterm=NONE
  hi ktStatement ctermfg=120 ctermbg=NONE cterm=NONE
  hi pythonBuiltinFunc ctermfg=214 ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=192 ctermbg=NONE cterm=NONE
  hi pythonNone ctermfg=214 ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=203 ctermbg=NONE cterm=NONE
  hi goImport ctermfg=203 ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=120 ctermbg=NONE cterm=NONE
  hi rustKeyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=203 ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=120 ctermbg=NONE cterm=NONE
  hi rustModPathSep ctermfg=192 ctermbg=NONE cterm=NONE
  hi rustSelf ctermfg=214 ctermbg=NONE cterm=NONE
  hi rustLifetime ctermfg=214 ctermbg=NONE cterm=NONE
  hi rustAssert ctermfg=203 ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=192 ctermbg=NONE cterm=NONE
  hi phpMethod ctermfg=214 ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=214 ctermbg=NONE cterm=NONE
  hi phpMemberSelector ctermfg=208 ctermbg=NONE cterm=NONE
  hi phpUseClass ctermfg=120 ctermbg=NONE cterm=NONE
  hi phpUseAlias ctermfg=214 ctermbg=NONE cterm=NONE
  hi phpFunction ctermfg=214 ctermbg=NONE cterm=NONE
  hi phpFunctions ctermfg=214 ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=214 ctermbg=NONE cterm=NONE
  hi phpClassExtends ctermfg=120 ctermbg=NONE cterm=NONE
  hi phpType ctermfg=203 ctermbg=NONE cterm=NONE
  hi phpNullValue ctermfg=192 ctermbg=NONE cterm=NONE
  hi phpClassImplements ctermfg=120 ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi csUnspecifiedStatement ctermfg=208 ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=203 ctermbg=NONE cterm=NONE
  hi csUnsupportedStatement ctermfg=120 ctermbg=NONE cterm=NONE
  hi csLogicSymbols ctermfg=203 ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=120 ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=120 ctermbg=NONE cterm=NONE
  hi csConstant ctermfg=214 ctermbg=NONE cterm=NONE
  hi csAsync ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi fsharpModifier ctermfg=203 ctermbg=NONE cterm=NONE
  hi fsharpKeyChar ctermfg=192 ctermbg=NONE cterm=NONE
  hi fsharpLinq ctermfg=203 ctermbg=NONE cterm=NONE
  hi fsharpCoreClass ctermfg=203 ctermbg=NONE cterm=NONE
  hi fsharpAttribute ctermfg=208 ctermbg=NONE cterm=NONE
  hi fsharpOption ctermfg=214 ctermbg=NONE cterm=NONE
  hi swiftInterpolatedString ctermfg=120 ctermbg=NONE cterm=NONE
  hi swiftTypeDeclaration ctermfg=203 ctermbg=NONE cterm=NONE
  hi rubyModuleName ctermfg=208 ctermbg=NONE cterm=NONE
  hi rubyClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi rubyPseudoVariable ctermfg=120 ctermbg=NONE cterm=NONE
  hi rubyDefine ctermfg=208 ctermbg=NONE cterm=NONE
  hi rubyModule ctermfg=203 ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=120 ctermbg=NONE cterm=NONE
  hi rubyMethodName ctermfg=214 ctermbg=NONE cterm=NONE
  hi rubyControl ctermfg=203 ctermbg=NONE cterm=NONE
  hi rubyInterpolation ctermfg=120 ctermbg=NONE cterm=NONE
  hi rubyInterpolationDelimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi rubyBoolean ctermfg=192 ctermbg=NONE cterm=NONE
  hi rubyCurlyBlockDelimiter ctermfg=120 ctermbg=NONE cterm=NONE
  hi rubyBlockParameterList ctermfg=214 ctermbg=NONE cterm=NONE
  hi! link rubySymbol Identifier
  hi perlStatementPackage ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi perlMethod ctermfg=214 ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=214 ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=203 ctermbg=NONE cterm=NONE
  hi perlSubName ctermfg=208 ctermbg=NONE cterm=NONE
  hi haskellDeclKeyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=208 ctermbg=NONE cterm=NONE
  hi HaskellDerive ctermfg=203 ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=203 ctermbg=NONE cterm=NONE
  hi haskellLet ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaLocal ctermfg=208 ctermbg=NONE cterm=NONE
  hi luaFuncCall ctermfg=120 ctermbg=NONE cterm=NONE
  hi luaSpecialTable ctermfg=214 ctermbg=NONE cterm=NONE
  hi luaFuncKeyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi luaSpecialValue ctermfg=214 ctermbg=NONE cterm=NONE
  hi moonInterpDelim ctermfg=192 ctermbg=NONE cterm=NONE
  hi moonInterp ctermfg=120 ctermbg=NONE cterm=NONE
  hi moonSpecialOp ctermfg=192 ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=203 ctermbg=NONE cterm=NONE
  hi dImport ctermfg=120 ctermbg=NONE cterm=NONE
  hi paramlist ctermfg=120 ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=203 ctermbg=NONE cterm=NONE
  hi dConstant ctermfg=214 ctermbg=NONE cterm=NONE
  hi dTypedef ctermfg=208 ctermbg=NONE cterm=NONE
  hi dBranch ctermfg=208 ctermbg=NONE cterm=NONE
  hi scalaKeywordModifier ctermfg=203 ctermbg=NONE cterm=NONE
  hi scalaSpecial ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link scalaSquareBracketsBrackets Delimiter
  hi elixirBoolean ctermfg=192 ctermbg=NONE cterm=NONE
  hi! link elixirTupleDelimiter Delimiter
  hi elixirPrivateDefine ctermfg=208 ctermbg=NONE cterm=NONE
  hi elixirAtom ctermfg=120 ctermbg=NONE cterm=NONE
  hi elixirKeyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi ocamlSigEncl ctermfg=214 ctermbg=NONE cterm=NONE
  hi ocamlKeyChar ctermfg=192 ctermbg=NONE cterm=NONE
  hi ocamlArrow ctermfg=192 ctermbg=NONE cterm=NONE
  hi ocamlModule ctermfg=120 ctermbg=NONE cterm=NONE
  hi ocamlModParam ctermfg=120 ctermbg=NONE cterm=NONE
  hi ocamlModParam1 ctermfg=214 ctermbg=NONE cterm=NONE
  hi ocamlStructEncl ctermfg=208 ctermbg=NONE cterm=NONE
  hi ocamlFullMod ctermfg=214 ctermbg=NONE cterm=NONE
  hi ocamlFuncWith ctermfg=120 ctermbg=NONE cterm=NONE
  hi ocamlConstructor ctermfg=203 ctermbg=NONE cterm=NONE
  hi ocamlModPath ctermfg=120 ctermbg=NONE cterm=NONE
  hi fortranStructure ctermfg=120 ctermbg=NONE cterm=NONE
  hi fortranUnitHeader ctermfg=203 ctermbg=NONE cterm=NONE
  hi fortranCall ctermfg=208 ctermbg=NONE cterm=NONE
  hi fortranReadWrite ctermfg=120 ctermbg=NONE cterm=NONE
  hi fortranIO ctermfg=214 ctermbg=NONE cterm=NONE
  hi clojureDefine ctermfg=208 ctermbg=NONE cterm=NONE
  hi clojureSpecial ctermfg=214 ctermbg=NONE cterm=NONE
  hi clojureDispatch ctermfg=192 ctermbg=NONE cterm=NONE
  hi erlangAtom ctermfg=120 ctermbg=NONE cterm=NONE
  hi erlangLocalFuncRef ctermfg=214 ctermbg=NONE cterm=NONE
  hi erlangType ctermfg=203 ctermbg=NONE cterm=NONE
  hi erlangLocalFuncCall ctermfg=120 ctermbg=NONE cterm=NONE
  hi erlangGlobalFuncCall ctermfg=214 ctermbg=NONE cterm=NONE
  hi erlangMap ctermfg=192 ctermbg=NONE cterm=NONE
  hi erlangVariable ctermfg=250 ctermbg=NONE cterm=NONE
  hi lispFunc ctermfg=208 ctermbg=NONE cterm=NONE
  hi lispKey ctermfg=214 ctermbg=NONE cterm=NONE
  hi lispDecl ctermfg=203 ctermbg=NONE cterm=NONE
  hi lispVar ctermfg=120 ctermbg=NONE cterm=NONE
  hi lispEscapeSpecial ctermfg=120 ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=203 ctermbg=NONE cterm=NONE
  hi shDerefSimple ctermfg=120 ctermbg=NONE cterm=NONE
  hi shTestOpr ctermfg=208 ctermbg=NONE cterm=NONE
  hi shFunctionOne ctermfg=214 ctermbg=NONE cterm=NONE
  hi shCommandSub ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link shQuote Delimiter
  hi! link shCmdSubRegion Delimiter
  hi! link shRange Delimiter
  hi zshSubst ctermfg=214 ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=120 ctermbg=NONE cterm=NONE
  hi zshOptStart ctermfg=203 ctermbg=NONE cterm=NONE
  hi zshOption ctermfg=208 ctermbg=NONE cterm=NONE
  hi zshVariableDef ctermfg=120 ctermbg=NONE cterm=NONE
  hi zshFunction ctermfg=203 ctermbg=NONE cterm=NONE
  hi zshShortDeref ctermfg=120 ctermbg=NONE cterm=NONE
  hi! link zshSubstDelim Delimiter
  hi fishKeyword ctermfg=203 ctermbg=NONE cterm=NONE
  hi vimMap ctermfg=203 ctermbg=NONE cterm=NONE
  hi vimFuncName ctermfg=214 ctermbg=NONE cterm=NONE
  hi vimFunction ctermfg=214 ctermbg=NONE cterm=NONE
  hi vimOperParen ctermfg=120 ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=214 ctermbg=NONE cterm=NONE
  hi vimLet ctermfg=203 ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=214 ctermbg=NONE cterm=NONE
  hi vimSetEqual ctermfg=120 ctermbg=NONE cterm=NONE
  hi vimAutoCmd ctermfg=203 ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=208 ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=120 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=203 ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=208 ctermbg=NONE cterm=NONE
  hi diffOldFile ctermfg=192 ctermbg=NONE cterm=NONE
  hi diffNewFile ctermfg=214 ctermbg=NONE cterm=NONE
  hi diffFile ctermfg=120 ctermbg=NONE cterm=NONE
  hi! link diffLine Comment
  hi helpHyperTextEntry ctermfg=203 ctermbg=NONE cterm=NONE
  hi! link helpSectionDelim Comment
  hi helpNote ctermfg=81 ctermbg=NONE cterm=NONE
  hi helpURL ctermfg=192 ctermbg=NONE cterm=underline
  hi helpCommand ctermfg=208 ctermbg=NONE cterm=NONE
  hi helpExample ctermfg=192 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=208 ctermbg=233 cterm=NONE
  hi ALEErrorSign ctermfg=203 ctermbg=233 cterm=NONE
  hi ALEInfoSign ctermfg=81 ctermbg=233 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=124 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=136 cterm=NONE
  hi ALEVirtualTextError ctermfg=240 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=240 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=240 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=240 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeDirSlash ctermfg=192 ctermbg=NONE cterm=NONE
  hi! link NERDTreeLinkFile Comment
  hi NERDTreeLinkTarget ctermfg=120 ctermbg=NONE cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyNumber ctermfg=214 ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=250 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=192 ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=192 ctermbg=NONE cterm=NONE
  hi Sneak ctermfg=NONE ctermbg=64 cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=Grey cterm=NONE
  hi LineNr ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=Black cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=bold
  hi MoreMsg ctermfg=White ctermbg=Grey cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=Grey cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=Green cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=White cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=Grey cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi TabLine ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Grey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=Grey cterm=italic
  hi PreCondit ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Red ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  hi Special ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Green ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Green ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Character ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Float ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Green ctermbg=NONE cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi markdownLinkText ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=Red ctermbg=NONE cterm=NONE
  hi markdownHeadingDelimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=Yellow ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi mkdCodeDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi mkdID ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=Red ctermbg=NONE cterm=NONE
  hi mkdCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi mkdHeading ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rstInlineLiteral ctermfg=Green ctermbg=NONE cterm=NONE
  hi rstTableLines ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi texOnlyMath ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi texSection ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi texBeginEndName ctermfg=Red ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi xmlEndTag ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi xmlAttrib ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi cssUnitDecorators ctermfg=Green ctermbg=NONE cterm=NONE
  hi cssFunctionName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi cssAttr ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=Red ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi sassClassChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=Red ctermbg=NONE cterm=NONE
  hi scssForKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi scssInterpolationDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi scssFunctionName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi scssDefault ctermfg=Red ctermbg=NONE cterm=NONE
  hi scssMixinName ctermfg=Red ctermbg=NONE cterm=NONE
  hi lessClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi lessMixinChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link javaScriptBraces Delimiter
  hi! link javaScriptParens Delimiter
  hi javaScriptFunction ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi javaScriptGlobal ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi javaScriptNull ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi javaScriptOperator ctermfg=Red ctermbg=NONE cterm=NONE
  hi jsOperatorKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsExceptions Exception
  hi typescriptLabel ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons typescriptBraces
  hi typescriptGlobalObjects ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link typescriptOpSymbols Operator
  hi typescriptOperator ctermfg=Red ctermbg=NONE cterm=NONE
  hi typescriptInterpolationDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi typescriptBranch ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dartTypedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=Green ctermbg=NONE cterm=NONE
  hi dartBranch ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=Green ctermbg=NONE cterm=NONE
  hi dartConstant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi coffeeSpecialVar ctermfg=Green ctermbg=NONE cterm=NONE
  hi coffeeSpecialIdent ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi coffeeInterp ctermfg=Green ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi purescriptModuleParams ctermfg=Green ctermbg=NONE cterm=NONE
  hi purescriptOperatorTypeSig ctermfg=Red ctermbg=NONE cterm=NONE
  hi purescriptOperatorFunction ctermfg=Green ctermbg=NONE cterm=NONE
  hi javaScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaVarArg ctermfg=Green ctermbg=NONE cterm=NONE
  hi javaStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi javaTypedef ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi javaAnnotation ctermfg=Green ctermbg=NONE cterm=NONE
  hi ktModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi ktStructure ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ktStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi pythonBuiltinFunc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi pythonNone ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi goImport ctermfg=Red ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi rustKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=Red ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=Green ctermbg=NONE cterm=NONE
  hi rustModPathSep ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi rustSelf ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustLifetime ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustAssert ctermfg=Red ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi phpMethod ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpMemberSelector ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi phpUseClass ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpUseAlias ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpFunction ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpFunctions ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpClassExtends ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpType ctermfg=Red ctermbg=NONE cterm=NONE
  hi phpNullValue ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi phpClassImplements ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi csUnspecifiedStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi csUnsupportedStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi csLogicSymbols ctermfg=Red ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=Green ctermbg=NONE cterm=NONE
  hi csConstant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csAsync ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi fsharpModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpKeyChar ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi fsharpLinq ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpCoreClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpAttribute ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fsharpOption ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi swiftInterpolatedString ctermfg=Green ctermbg=NONE cterm=NONE
  hi swiftTypeDeclaration ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyModuleName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyPseudoVariable ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyDefine ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyModule ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyMethodName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyControl ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyInterpolation ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyInterpolationDelimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi rubyBoolean ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi rubyCurlyBlockDelimiter ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyBlockParameterList ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link rubySymbol Identifier
  hi perlStatementPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi perlMethod ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlSubName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi haskellDeclKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi HaskellDerive ctermfg=Red ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=Red ctermbg=NONE cterm=NONE
  hi haskellLet ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi luaLocal ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi luaFuncCall ctermfg=Green ctermbg=NONE cterm=NONE
  hi luaSpecialTable ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi luaFuncKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi luaSpecialValue ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi moonInterpDelim ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi moonInterp ctermfg=Green ctermbg=NONE cterm=NONE
  hi moonSpecialOp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi dImport ctermfg=Green ctermbg=NONE cterm=NONE
  hi paramlist ctermfg=Green ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=Red ctermbg=NONE cterm=NONE
  hi dConstant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dTypedef ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dBranch ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi scalaKeywordModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi scalaSpecial ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link scalaSquareBracketsBrackets Delimiter
  hi elixirBoolean ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi! link elixirTupleDelimiter Delimiter
  hi elixirPrivateDefine ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi elixirAtom ctermfg=Green ctermbg=NONE cterm=NONE
  hi elixirKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ocamlSigEncl ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ocamlKeyChar ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi ocamlArrow ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi ocamlModule ctermfg=Green ctermbg=NONE cterm=NONE
  hi ocamlModParam ctermfg=Green ctermbg=NONE cterm=NONE
  hi ocamlModParam1 ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ocamlStructEncl ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ocamlFullMod ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ocamlFuncWith ctermfg=Green ctermbg=NONE cterm=NONE
  hi ocamlConstructor ctermfg=Red ctermbg=NONE cterm=NONE
  hi ocamlModPath ctermfg=Green ctermbg=NONE cterm=NONE
  hi fortranStructure ctermfg=Green ctermbg=NONE cterm=NONE
  hi fortranUnitHeader ctermfg=Red ctermbg=NONE cterm=NONE
  hi fortranCall ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi fortranReadWrite ctermfg=Green ctermbg=NONE cterm=NONE
  hi fortranIO ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi clojureDefine ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi clojureSpecial ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi clojureDispatch ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi erlangAtom ctermfg=Green ctermbg=NONE cterm=NONE
  hi erlangLocalFuncRef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi erlangType ctermfg=Red ctermbg=NONE cterm=NONE
  hi erlangLocalFuncCall ctermfg=Green ctermbg=NONE cterm=NONE
  hi erlangGlobalFuncCall ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi erlangMap ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi erlangVariable ctermfg=White ctermbg=NONE cterm=NONE
  hi lispFunc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi lispKey ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi lispDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi lispVar ctermfg=Green ctermbg=NONE cterm=NONE
  hi lispEscapeSpecial ctermfg=Green ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi shDerefSimple ctermfg=Green ctermbg=NONE cterm=NONE
  hi shTestOpr ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi shFunctionOne ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi shCommandSub ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link shQuote Delimiter
  hi! link shCmdSubRegion Delimiter
  hi! link shRange Delimiter
  hi zshSubst ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=Green ctermbg=NONE cterm=NONE
  hi zshOptStart ctermfg=Red ctermbg=NONE cterm=NONE
  hi zshOption ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi zshVariableDef ctermfg=Green ctermbg=NONE cterm=NONE
  hi zshFunction ctermfg=Red ctermbg=NONE cterm=NONE
  hi zshShortDeref ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link zshSubstDelim Delimiter
  hi fishKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi vimMap ctermfg=Red ctermbg=NONE cterm=NONE
  hi vimFuncName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimFunction ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimOperParen ctermfg=Green ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimLet ctermfg=Red ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimSetEqual ctermfg=Green ctermbg=NONE cterm=NONE
  hi vimAutoCmd ctermfg=Red ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=Green ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=Red ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi diffOldFile ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi diffNewFile ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi diffFile ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link diffLine Comment
  hi helpHyperTextEntry ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link helpSectionDelim Comment
  hi helpNote ctermfg=Blue ctermbg=NONE cterm=NONE
  hi helpURL ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi helpCommand ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi helpExample ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=Grey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=Grey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=Grey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=Black cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=Black cterm=NONE
  hi ALEVirtualTextError ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi NERDTreeDirSlash ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi! link NERDTreeLinkFile Comment
  hi NERDTreeLinkTarget ctermfg=Green ctermbg=NONE cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi StartifyNumber ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=White ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Sneak ctermfg=NONE ctermbg=Black cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #24221c           235               Black
" Color: grey          #473f31           233               Grey
" Color: lightgrey     #87765d           240               LightGrey
" Color: golden        #d4b07b           250               White
" Color: red           #e56b55           203               Red
" Color: orange        #e18245           208               DarkYellow
" Color: yellow        #e5a440           214               Yellow
" Color: lemon         #bfab36           192               LightGreen
" Color: green         #99b05f           120               Green
" Color: brown         #bd975f           248               Brown
" Color: blue          #949fb4           81                Blue
" Color: magenta       #d261a5           139               Magenta
" Color: darkorange    #512c13           136               Black
" Color: darkred       #562022           124               Black
" Color: darkgreen     #303a1a           64                Black
" Color: darkblue      #1e2c3e           24                Black
" Term colors: grey red green orange blue magenta lemon golden
" Term colors: grey red green yellow
" Term colors: blue magenta lemon golden
" Color: unused #000000 0 0
" vim: et ts=2 sw=2
