" Name:         Desert Night
" Description:  Dark, Warm, Eye-friendly Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-desert-night/
" License:      MIT && Anti-996
" Last Updated: Tue 02 Jul 2019 12:53:48 PM CST

" Generated by Colortemplate v2.0.0b3

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'desert-night'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Structure Type
hi! link Define PreProc
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#473f31', '#e56060', '#b2ad45', '#e18245',
        \ '#949fb4', '#d261a5', '#9db65d', '#d4b07b', '#473f31', '#e56060',
        \ '#b2ad45', '#e18245', '#949fb4', '#d261a5', '#9db65d', '#d4b07b']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d4b07b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#303a1a guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#1e2c3e guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#562022 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#512c13 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#473f31 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e56060 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#e18245 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#87765d guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#473f31 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#473f31 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#24221c guibg=#9db65d guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#24221c guibg=#d4b07b guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#949fb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#473f31 guisp=NONE gui=underline cterm=underline
  hi SignColumn guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#e56060 guibg=NONE guisp=#e56060 gui=NONE cterm=NONE
  hi SpellCap guifg=#e18245 guibg=NONE guisp=#e18245 gui=NONE cterm=NONE
  hi SpellLocal guifg=#949fb4 guibg=NONE guisp=#949fb4 gui=NONE cterm=NONE
  hi SpellRare guifg=#d261a5 guibg=NONE guisp=#d261a5 gui=NONE cterm=NONE
  hi StatusLine guifg=#24221c guibg=#d4b07b guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#d4b07b guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#24221c guibg=#d4b07b guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#473f31 guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#473f31 guisp=NONE gui=italic cterm=italic
  hi WildMenu guifg=#d4b07b guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#d261a5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#949fb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#e56060 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Typedef guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#87765d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#24221c guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#d4b07b guibg=#24221c guisp=NONE gui=bold cterm=bold
  hi cssProp guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsParens Delimiter
  hi! link jsIfElseBraces Delimiter
  hi typescriptEndColons guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptBraces Delimiter
  hi! link typescriptParens Delimiter
  hi! link typescriptEndColons Delimiter
  hi pythonStatement guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPackage guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goImport guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustExternCrate guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustSigil guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustModPath guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link rustCommentLineDoc Comment
  hi phpVarSelector guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi rubyMethodName guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartClassDecl guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartStorageClass guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementPackage guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementStorage guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlMethod guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDecl guifg=#e56060 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellOperators guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shFunction guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDerefSimple guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shQuote guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shDerefVar guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonQuote guifg=#b2ad45 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonKeyword guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlKey guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlKey guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#e18245 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyNumber guifg=#9db65d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#e18245 guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#e56060 guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#949fb4 guibg=#473f31 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#562022 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#512c13 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#87765d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak guifg=NONE guibg=#562022 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=250 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=250 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=250 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=235 cterm=NONE
  hi Conceal ctermfg=240 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=250 ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi CursorLineNr ctermfg=250 ctermbg=233 cterm=NONE
  hi LineNr ctermfg=240 ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=64 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=24 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=124 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=136 cterm=NONE
  hi Directory ctermfg=120 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=233 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=208 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=208 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=120 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=240 ctermbg=233 cterm=NONE
  hi Folded ctermfg=240 ctermbg=233 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=233 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=233 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=250 ctermbg=233 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=233 cterm=NONE
  hi PmenuSel ctermfg=235 ctermbg=120 cterm=NONE
  hi PmenuThumb ctermfg=235 ctermbg=250 cterm=NONE
  hi Question ctermfg=81 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=233 cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=208 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=81 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=139 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=235 ctermbg=250 cterm=NONE
  hi StatusLineNC ctermfg=250 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=250 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=250 ctermbg=235 cterm=NONE
  hi TabLineSel ctermfg=235 ctermbg=250 cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=233 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=233 cterm=italic
  hi WildMenu ctermfg=250 ctermbg=233 cterm=NONE
  hi PreCondit ctermfg=139 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=81 ctermbg=NONE cterm=NONE
  hi Title ctermfg=203 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=203 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=203 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=NONE cterm=bold
  hi Typedef ctermfg=203 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=203 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=203 ctermbg=NONE cterm=NONE
  hi Label ctermfg=208 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=208 ctermbg=NONE cterm=NONE
  hi Special ctermfg=208 ctermbg=NONE cterm=NONE
  hi Type ctermfg=208 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi Function ctermfg=120 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=120 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=120 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=120 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=192 ctermbg=NONE cterm=NONE
  hi String ctermfg=192 ctermbg=NONE cterm=NONE
  hi Character ctermfg=192 ctermbg=NONE cterm=NONE
  hi Number ctermfg=192 ctermbg=NONE cterm=NONE
  hi Float ctermfg=192 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=120 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=120 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=120 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=240 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=120 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi ToolbarButton ctermfg=250 ctermbg=235 cterm=bold
  hi cssProp ctermfg=208 ctermbg=NONE cterm=NONE
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsParens Delimiter
  hi! link jsIfElseBraces Delimiter
  hi typescriptEndColons ctermfg=192 ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptBraces Delimiter
  hi! link typescriptParens Delimiter
  hi! link typescriptEndColons Delimiter
  hi pythonStatement ctermfg=208 ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=203 ctermbg=NONE cterm=NONE
  hi goImport ctermfg=208 ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=203 ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=208 ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=192 ctermbg=NONE cterm=NONE
  hi! link rustCommentLineDoc Comment
  hi phpVarSelector ctermfg=192 ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi rubyMethodName ctermfg=208 ctermbg=NONE cterm=NONE
  hi dartClassDecl ctermfg=208 ctermbg=NONE cterm=NONE
  hi dartStorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=203 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=208 ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=203 ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=208 ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=203 ctermbg=NONE cterm=NONE
  hi haskellOperators ctermfg=192 ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=208 ctermbg=NONE cterm=NONE
  hi shDerefSimple ctermfg=120 ctermbg=NONE cterm=NONE
  hi shQuote ctermfg=192 ctermbg=NONE cterm=NONE
  hi shDerefVar ctermfg=208 ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=192 ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=208 ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=208 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=208 ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=120 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=208 ctermbg=233 cterm=NONE
  hi ALEErrorSign ctermfg=203 ctermbg=233 cterm=NONE
  hi ALEInfoSign ctermfg=81 ctermbg=233 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=124 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=136 cterm=NONE
  hi ALEVirtualTextError ctermfg=240 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=240 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=240 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=240 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=124 cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=Grey cterm=NONE
  hi LineNr ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=Black cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Green ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=Grey cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=Green cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=White cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=Grey cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=Grey cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=Black ctermbg=White cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi TabLine ctermfg=White ctermbg=Grey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=White cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Grey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=Grey cterm=italic
  hi WildMenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=bold
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Red ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Green ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Green ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi String ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Character ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Number ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Float ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Green ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Green ctermbg=NONE cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Green ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi cssProp ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsParens Delimiter
  hi! link jsIfElseBraces Delimiter
  hi typescriptEndColons ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptBraces Delimiter
  hi! link typescriptParens Delimiter
  hi! link typescriptEndColons Delimiter
  hi pythonStatement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi goImport ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=Red ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rustModPath ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link rustCommentLineDoc Comment
  hi phpVarSelector ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi rubyMethodName ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dartClassDecl ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi dartStorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi haskellOperators ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi shDerefSimple ctermfg=Green ctermbg=NONE cterm=NONE
  hi shQuote ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi shDerefVar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=Green ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=Grey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=Grey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=Grey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=Black cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=Black cterm=NONE
  hi ALEVirtualTextError ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=Black cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" QuickFixLine      -> Search
" StatusLineTerm    -> StatusLine
" StatusLineTermNC  -> StatusLineNC
" Structure         -> Type
" Define            -> PreProc
" Debug             -> Special
" Include           -> PreProc
" Macro             -> PreProc
" Repeat            -> Statement
" lCursor           -> Cursor
" Background: dark
" Color: black         #24221c           235               Black
" Color: grey          #473f31           233               Grey
" Color: lightgrey     #87765d           240               LightGrey
" Color: golden        #d4b07b           250               White
" Color: red           #e56060           203               Red
" Color: orange        #e18245           208               DarkYellow
" Color: lemon         #b2ad45           192               Yellow
" Color: green         #9db65d           120               Green
" Color: blue          #949fb4           81                Blue
" Color: magenta       #d261a5           139               Magenta
" Color: darkorange    #512c13           136               Black
" Color: darkred       #562022           124               Black
" Color: darkgreen     #303a1a           64                Black
" Color: darkblue      #1e2c3e           24                Black
" Term colors: grey red lemon orange blue magenta green golden
" Term colors: grey red lemon orange
" Term colors: blue magenta green golden
" Variant: gui
" if get(g:, '@optionprefix_transp_bg', 0) && !has('gui_running')
" Variant: 256 8
" if get(g:, '@optionprefix_transp_bg', 0)
" Variant: gui 256 8
"     Normal           golden            none
"     Terminal         golden            none
" else
"     Normal           golden             black
"     Terminal         golden            black
" endif
" ColorColumn          fg                black
" Conceal              lightgrey         none
" Cursor               golden            black
" CursorColumn         none              grey
" CursorLine           none              grey
" CursorLineNr         golden            grey
" LineNr               lightgrey         grey
" DiffAdd              none              darkgreen
" DiffChange           none              darkblue
" DiffDelete           none              darkred
" DiffText             none              darkorange
" Directory            green             none
" EndOfBuffer          grey              none
" ErrorMsg             red               none              bold
" WarningMsg           orange            none              bold
" ModeMsg              orange            none
" MoreMsg              green             none
" FoldColumn           lightgrey         grey
" Folded               lightgrey         grey
" IncSearch            none              grey              underline
" MatchParen           none              none              bold
" NonText              grey              none
" Pmenu                golden            grey
" PmenuSbar            none              grey
" PmenuSel             black             green
" PmenuThumb           black             golden
" Question             blue              none
" Search               none              grey              underline
" SignColumn           none              grey
" SpellBad             red               none              s=red
" SpellCap             orange            none              s=orange
" SpellLocal           blue              none              s=blue
" SpellRare            magenta           none              s=magenta
" StatusLine           black             golden
" StatusLineNC         golden            black
" TabLine              golden            grey
" TabLineFill          golden            black
" TabLineSel           black             golden
" VertSplit            grey              black
" Visual               none              grey
" VisualNOS            none              grey              italic
" WildMenu             golden            grey
" PreCondit            magenta           none
" Todo                 blue              none
" Title                red               none
" PreProc              red               none
" Conditional          red               none
" Exception            red               none
" Error                red               none              bold
" Typedef              red               none
" StorageClass         red               none
" SpecialKey           red               none
" Label                orange            none
" Operator             orange            none
" Special              orange            none
" Type                 orange            none
" Keyword              orange            none
" Function             green             none
" Identifier           green             none
" Statement            green             none
" Tag                  green             none
" Delimiter            lemon             none
" String               lemon             none
" Character            lemon             none
" Number               lemon             none
" Float                lemon             none
" Constant             green             none
" Boolean              green             none
" SpecialChar          green             none
" Comment              lightgrey         none              italic
" SpecialComment       green             none
" Ignore               lightgrey         none
" Underlined           none              none              underline
" CursorIM             none              fg
" ToolbarLine          none              black
" ToolbarButton        golden            black             bold
" cssProp              orange            none
" jsFuncBraces      -> Delimiter
" jsFuncParens      -> Delimiter
" jsObjectBraces    -> Delimiter
" jsParens          -> Delimiter
" jsIfElseBraces    -> Delimiter
" typescriptEndColons  lemon             none
" typescriptExceptions -> Exception
" typescriptBraces  -> Delimiter
" typescriptParens  -> Delimiter
" typescriptEndColons -> Delimiter
" pythonStatement      orange            none
" goPackage            red               none
" goImport             orange            none
" rustExternCrate      red               none
" rustSigil            orange            none
" rustModPath          lemon             none
" rustCommentLineDoc -> Comment
" phpVarSelector       lemon             none
" phpParent         -> Delimiter
" rubyMethodName       orange            none
" dartClassDecl        orange            none
" dartStorageClass     orange            none
" perlStatementPackage red               none
" perlStatementInclude orange            none
" perlStatementStorage red               none
" perlMethod           orange            none
" haskellDecl          red               none
" haskellOperators     lemon             none
" shFunction           orange            none
" shDerefSimple        green             none
" shQuote              lemon             none
" shDerefVar           orange            none
" jsonQuote            lemon             none
" jsonKeyword          orange            none
" yamlKey              orange            none
" tomlKey              orange            none
" StartifySection      orange            none
" StartifyNumber       green             none
" ALEWarningSign       orange            grey
" ALEErrorSign         red               grey
" ALEInfoSign          blue              grey
" ALEError             none              darkred
" ALEWarning           none              darkorange
" ALEVirtualTextError  lightgrey         none
" ALEVirtualTextWarning lightgrey        none
" ALEVirtualTextInfo   lightgrey         none
" ALEVirtualTextStyleError            -> ALEVirtualTextError
" ALEVirtualTextStyleWarning          -> ALEVirtualTextWarning
" CocHighlightText     none              none              bold
" CocCodeLens          lightgrey         none
" CocErrorSign      -> ALEErrorSign
" CocWarningSign    -> ALEWarningSign
" CocInfoSign       -> ALEInfoSign
" CocHintSign       -> Label
" CocErrorHighlight -> ALEError
" CocWarningHighlight -> ALEWarning
" CocInfoHighlight  -> ALEInfo
" CocWarningVirtualText -> ALEVirtualTextWarning
" CocErrorVirtualText -> ALEVirtualTextError
" CocInfoVirtualText -> ALEVirtualTextInfo
" CocHintVirtualText -> ALEVirtualTextInfo
" CocCodeLens       -> ALEVirtualTextInfo
" MatchParenCur        none              none              bold
" MatchWord            none              none              underline
" MatchWordCur         none              none              underline
" Sneak                none              darkred
" Variant: 2
" Color: unused #000000 0 0
" Normal               unused unused
" ColorColumn          unused unused reverse
" Conceal              unused unused
" Cursor               unused unused
" CursorColumn         unused unused reverse
" CursorLine           unused unused underline
" CursorLineNr         unused unused reverse,italic,bold,underline
" DiffAdd              unused unused reverse,underline
" DiffChange           unused unused reverse,underline
" DiffDelete           unused unused reverse,underline
" DiffText             unused unused bold,reverse,underline
" Directory            unused unused
" EndOfBuffer          unused unused
" ErrorMsg             unused unused bold,reverse,italic
" FoldColumn           unused unused reverse
" Folded               unused unused italic,reverse,underline
" IncSearch            unused unused reverse,bold,italic
" LineNr               unused unused reverse
" MatchParen           unused unused bold,underline
" ModeMsg              unused unused
" MoreMsg              unused unused
" NonText              unused unused
" Pmenu                unused unused reverse
" PmenuSbar            unused unused
" PmenuSel             unused unused
" PmenuThumb           unused unused
" Question             unused unused standout
" Search               unused unused underline,italic
" SignColumn           unused unused reverse
" SpecialKey           unused unused bold
" SpellBad             unused unused underline,italic
" SpellCap             unused unused underline,italic
" SpellLocal           unused unused underline,italic
" SpellRare            unused unused underline,italic
" StatusLine           unused unused reverse,bold
" StatusLineNC         unused unused reverse
" TabLine              unused unused reverse,underline,italic
" TabLineFill          unused unused reverse,underline
" TabLineSel           unused unused bold
" Title                unused unused bold
" VertSplit            unused unused reverse
" Visual               unused unused reverse
" VisualNOS            unused unused
" WarningMsg           unused unused standout
" WildMenu             unused unused bold
" Comment              unused unused italic
" Constant             unused unused bold,italic
" Error                unused unused reverse
" Identifier           unused unused italic
" Ignore               unused unused
" PreProc              unused unused italic
" Special              unused unused bold,italic
" Statement            unused unused bold
" Todo                 unused unused bold,underline
" Type                 unused unused bold
" Underlined           unused unused underline
" CursorIM             unused unused
" ToolbarLine          unused unused reverse
" ToolbarButton        unused unused bold,reverse
